### PR TITLE
FBX, OBJ & DAE Models & Rigs

### PR DESCRIPTION
**Pull request by cyb3rdog**
These first attempt exports were exported AS IS.
- FBX had warnings (usupported maps/textures, animation curves, skin definitions...)
- DAE had warnings (usupported maps/textures, animation curves, skin definitions...)
- OBJ had warnings (shaders)

### CODE REVIEW

**Comment by randym32** [comment]
This places some exported 3d object files into the same folder as the maya models.   (Both pretty in a maya project folder, with a bunch of tooling around maya).  I recommend a seperate folder or repo for the converted/exported assets.  Some ideas "/exports" , "/assets/exports" or similar.

**Comment by cyb3rdog** [comment]
I was considering exactly this same topic regarding location of the files,
and I have chosen to locate the asset files to the very same folder mainly
for following reasons:
- whole folder structure would need to be replicated, which will cause more
difficult synchronization and tracking in case of changes and potentially
more user errors
- /assets subfolder in project root folder is conventional even for other
engines (for example it is also part of unity directory structure which can
process all assets including the .ma in case maya is installed)
- potential future migration from of the developement tools from maya to
unity (porting sh and python tools of AnkiMenu) would be easier and more
transparent while preserving same directory structure
- ease of use of possible automation, conversion or batch tools


Dne čt 27. kvě 2021 14:07 uživatel Randall Maas ***@***.***>
napsal:

**Comment by randym32** [comment]
My preference is that if there is a project to be set up for different tool set, that should be a different repo.  The current repo -- all of the files, scripts, docs -- are set up for a Maya project.   Or, at the least, a completely separate directory tree at the  very top level for the different environment.

I am not understanding the issue with the whole folder structure, and replication.   Mixing the source files and the exported ones in the same folder (rather than segrating them by their logical stage or type) is not a good practice, and can cause all sorts of problems.  One temptation is to editing the downstream (exported) file, but this will not be reflected in the source files.  

The automated tools, don't currently exist for the .fbx (etc) files, and  should always take a configurable location.  The current maya scripts shouldn't be modified to try to do double duty for multiple tool chains and projects.  They should support Maya (such as it is).  Other environments/tools can start with those, but should create their structure and support.  

I would recommend at a minimum to place them into  /assets/exports  or  similar if /exports is a concern

**Comment by cyb3rdog** [comment]
Well I quite dont understand what is asked from me here and I am definitelly not arguing against your recommendations, preferrences or practices.

We are perhaps talking here about two different topics, where first - my initiative (and perhaps even common shared community initiative) aims to replace commercial maya with a free development enviroment which is indeed a different project and with the highest probability will not be maintained in this DDL repository, but instead in a repository where participation will be more opened and community driven (maybe in my fork, maybe in someone elses, who know who will get this farest) That is why i have decided that the assets in my fork will be orginized the way I have explained above for reasons I described above.

Upon an explicit request for sharing the coverted assets, (which is a second topic), I created this pr, which originates from my repository and my structuralization. In case you prefer to have the files organized differently, you have following options:
- perform a manual merge with re-locating the assets correspondingly to your preferrences
- close this pr, and perform the pull from my fork yourselves, again however you like to..
- move the assets correspondingly to your prefference outside of the merging tree, by downloading, adding and commiting them manually
- convert the assets yourselves...
- ecetera...

To be clear, i dont have any desire of forcing you into anything at all, and I simply contribute with what I have been asked for, I will deffinitelly not be doing a branch, changing it the way you preffer, for doing a pr just for that. Thats why i dont see point in this discussion, even i do like exchanging oppions :)

Have a great day Randy! :)
Cheers

**Comment by randym32** [comment]
My request is that these converted files be placed into a separate folder (not the same as the maya model files).

Randy

**Comment by bussardrobbie** [comment]
I like what is being done here and I want to encourage it. However, it's important that we do get the dir structure decent; @randym32 can you please review my new branch of @cyb3rdog's fork (link below). Specifically if you can please review the directory structure, for example, in assets/rigs/Base, you'll see that I split out each file format into its own subdirectory so that the correct file can be easily found for each different tool. This was the best way (that I saw) to keep everything organized without creating duplicates anywhere.

Please let me know what you think:
https://github.com/cyb3rdog/vectors-free-animations/tree/directory-cleanup

**Comment by cyb3rdog** [comment]
Closed and replaced by [#5 FBX, OBJ & DAE - Models & Rigs](https://github.com/digital-dream-labs/vector-animations-raw/pull/5)

**Pull request closed without merging**
